# https://dev.to/abbazs/a-step-by-step-guide-for-starting-a-mosquitto-broker-service-in-a-containers-with-docker-compose-1j8i

version: '3.8'
services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
    - type: bind
      source: ./config/
      target: /mosquitto/config/
      read_only: false
    - type: bind
      source: ./log/
      target: /mosquitto/log/
      read_only: false
    - type: volume
      source: data
      target: /mosquitto/data/
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: host
    - target: 9001
      published: 9001
      protocol: tcp
      mode: host

volumes:
   data:
       name: "mqtt-broker-data"
