x-user: &user
  user: 8888:888

services:
  etl:
#    <<: *user
#    user: "8888:888"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONDA_ENV_FILE: environment.dev.yml
#    command: ["watchgod", "trade_price_etl.main"]
#    command: ["sleep", "5000"]
    command: /start.sh DEBUG