x-user: &user
  user: 8888:888

services:
  etl:
#    <<: *user
#    user: "8888:888"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONDA_ENV_FILE: environment.dev.yml
        HTTP_PROXY: http://host.docker.internal:7890
        HTTPS_PROXY: http://host.docker.internal:7890
#    command: ["watchgod", "trade_price_etl.main"]
#    command: ["sleep", "5000"]
    command: /start.sh DEBUG

  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
    - type: bind
      source: ./config/
      target: /mosquitto/config/
      read_only: false
    - type: bind
      source: ./log/
      target: /mosquitto/log/
      read_only: false
    - type: volume
      source: mqtt-broker-data
      target: /mosquitto/data/
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: host
    - target: 9001
      published: 9001
      protocol: tcp
      mode: host
    networks:
      - service-net