services:
  etl:
    image: ${IMAGE}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONDA_ENV_FILE: environment.yml
    command: /start.sh DEBUG
    volumes:
      - ../src/:/app
    networks:
      - service-net

  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
    - ./config:/mosquitto/config/
    - ./mqtt-broker-data:/mosquitto/data
    ports:
    - 1883:1883 # tcp broker port
    - 9001:9001
    - 8080:8080 # websocket
    networks:
      - service-net

networks:
  service-net:
    name: ${INTERNAL_NETWORK}

volumes:
   mqtt-broker-data:
       name: "mqtt-broker-data2"
