x-user: &user
  user: 8888:888

services:
  etl:
#    <<: *user
#    user: "8888:888"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONDA_ENV_FILE: environment.yml
#    command: ["watchgod", "trade_price_etl.main"]
#    command: ["sleep", "5000"]
    command: /start.sh DEBUG

  mqtt-broker:
#    <<: *user
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
    - ./config:/mosquitto/config/
#    - ./log:/mosquitto/log/:rw
    - ./mqtt-broker-data:/mosquitto/data
    ports:
    - 1883:1883
    - 9001:9001
    networks:
      - service-net