
services:

  etl:
    image: ${IMAGE}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONDA_ENV_FILE: environment.yml
    command: sleep 5000
    networks:
      - service-net

  mongodb:
    image: mongo:latest
    restart: always
    command: mongod --quiet --logpath /dev/null
#    ports:
#      - 27017:27017
    networks:
      - service-net


networks:
  service-net:
    name: ${INTERNAL_NETWORK}
#    external: true
